<a href="https://colab.research.google.com/github/mateuszrajca69/r/blob/main/ryan_13_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import pandas as pd
from io import StringIO

In [53]:
dane = \
''',A,B,C,D,E,F,G,H,I,J
0,1.0,2.0,3.0,4.0,5.0,,7.0,,9.0,10.0
1,11.0,12.0,,,15.0,16.0,,18.0,19.0,
2,,22.0,23.0,24.0,25.0,,,,29.0,30.0'''
df = pd.read_csv(StringIO(dane))
df

Unnamed: 0     A     B     C     D     E     F    G     H     I     J
0           0   1.0   2.0   3.0   4.0   5.0   NaN  7.0   NaN   9.0  10.0
1           1  11.0  12.0   NaN   NaN  15.0  16.0  NaN  18.0  19.0   NaN
2           2   NaN  22.0  23.0  24.0  25.0   NaN  NaN   NaN  29.0  30.0

In [54]:
df.isnull().sum() #Zidentyfikowanie brakujących danych w zbiorze danych

Unnamed: 0    0
A             1
B             0
C             1
D             1
E             0
F             2
G             2
H             2
I             0
J             1
dtype: int64

In [ ]:
#Wstawianie brakujących danych

In [55]:
from sklearn.impute import SimpleImputer  
import numpy as np
imp = SimpleImputer(missing_values=np.nan, strategy='mean') 
imp = imp.fit(df.values)
imputed_data = imp.transform(df.values)
imputed_data

array([[ 0.,  1.,  2.,  3.,  4.,  5., 16.,  7., 18.,  9., 10.],
       [ 1., 11., 12., 13., 14., 15., 16.,  7., 18., 19., 20.],
       [ 2.,  6., 22., 23., 24., 25., 16.,  7., 18., 29., 30.]])

In [70]:
df.to_csv('csv')

In [63]:
#Dane kategoryzujące
df = pd.DataFrame([
['zielony', 'M', 50.5, 'klasa1'],
['czerwony', 'L', 52.5, 'klasa2'], 
['niebieski', 'XL', 57.5, 'klasa1'],
['fioletowy','S',59.5 ,'klasa1'],
['czerwony','L',48.5 ,'klasa3'],
['zielony','XL',48.5 ,'klasa2'],
['brązowy','M',51.5 ,'klasa1'],
['fioletowy','L',53.5 ,'klasa3'],
['niebieski','S',61.5 ,'klasa3'],
['czerwony','XXL',65.5 ,'klasa1'],



])
df.columns = ['kolor', 'rozmiar', 'cena', 'etykiety klas']
df

kolor rozmiar  cena etykiety klas
0    zielony       M  50.5        klasa1
1   czerwony       L  52.5        klasa2
2  niebieski      XL  57.5        klasa1
3  fioletowy       S  59.5        klasa1
4   czerwony       L  48.5        klasa3
5    zielony      XL  48.5        klasa2
6    brązowy       M  51.5        klasa1
7  fioletowy       L  53.5        klasa3
8  niebieski       S  61.5        klasa3
9   czerwony     XXL  65.5        klasa1

In [57]:
map = {           #konwersja wartości porządkowych na wartości liczbowe, aby algorytm nauczania mógł prawidłowo odczytać wartości porządkowe
    'XXL' : 5,
    'S' : 4,
    'XL' : 3,
    'L' : 2,
    'M' : 1,
}
df['rozmiar'] = df['rozmiar'].map(map) #użycie funkcji map() do konwersji słów na liczby
df

kolor  rozmiar  cena etykiety klas
0    zielony        1  50.5        klasa1
1   czerwony        2  52.5        klasa2
2  niebieski        3  57.5        klasa1
3  fioletowy        4  59.5        klasa1
4   czerwony        2  48.5        klasa3
5    zielony        3  48.5        klasa2
6    brązowy        1  51.5        klasa1
7  fioletowy        2  53.5        klasa3
8  niebieski        4  61.5        klasa3
9   czerwony        5  65.5        klasa1

In [58]:
rev_map = {v: k for k, v in map.items()}   #proces odwrotny, czyli przywrócenie wartości porządkowych z wartości liczbowych
df['rozmiar'].map(rev_map)

0      M
1      L
2     XL
3      S
4      L
5     XL
6      M
7      L
8      S
9    XXL
Name: rozmiar, dtype: object

In [59]:
map_klasa = {label:idx for idx,label in enumerate(np.unique(df['etykiety klas']))} #konwersja przy użyciu funkcji enumerate()
map_klasa

{'klasa1': 0, 'klasa2': 1, 'klasa3': 2}

In [60]:
df['etykiety klas'] = df['etykiety klas'].map(map_klasa) #zastosowanie mapowania do zaimplementowania wartości liczbowej do zbioru danych
df

kolor  rozmiar  cena  etykiety klas
0    zielony        1  50.5              0
1   czerwony        2  52.5              1
2  niebieski        3  57.5              0
3  fioletowy        4  59.5              0
4   czerwony        2  48.5              2
5    zielony        3  48.5              1
6    brązowy        1  51.5              0
7  fioletowy        2  53.5              2
8  niebieski        4  61.5              2
9   czerwony        5  65.5              0

In [61]:
#alternatywna wersja funkcji mapowania poprzez użycie biblioteki sklearn i LabelEncoder
from sklearn.preprocessing import LabelEncoder 
klasa_et = LabelEncoder()
y = klasa_et.fit_transform(df['etykiety klas'].values)    # klasa_et.inverse_transform(y)
y

array([0, 1, 0, 0, 2, 1, 0, 2, 2, 0])

In [62]:
X = df[['kolor', 'rozmiar', 'cena']].values 
kolor_et = LabelEncoder()
X[:, 0] = kolor_et.fit_transform(X[:, 0]) #transformowanie pierwszej kolumny (w tym przypadku koloru) z wartości nominalnych na wartości liczbowe
X

array([[4, 1, 50.5],
       [1, 2, 52.5],
       [3, 3, 57.5],
       [2, 4, 59.5],
       [1, 2, 48.5],
       [4, 3, 48.5],
       [0, 1, 51.5],
       [2, 2, 53.5],
       [3, 4, 61.5],
       [1, 5, 65.5]], dtype=object)